const ligthVersion = {
  backgroundColor: '#FFFFFF',
  placeholderColor: '#000000b5',
  buttonBackColor: '#1d9bf0c4',
  inputBackColor: '#eff3f4',
  textColor: '#000000',
  navBarBack: '#eff3f4',
  focusText: '#AAB8C2',
  shadowText: '#AAB8C2',
  tabNavigationText: '#657786',
  tabBackground: '#E1E8ED',
  cardBackColor: '#eff3f4',
  modalBackColor: '#eff3f4',
  tintColor: '#000000',
  blue: '#1DA1F2',
  black: '#14171A',
  darkGray: '#657786',
  lightGray: '#AAB8C2',
  extraLightGray: '#E1E8ED',
  thinLightGray: '#F5F8FA',
  white: '#fff',
  breadCrumbContainer: '#eff3f4',
  containerBorderColor: '#D3D3D3',
  activeBreadCrumb: '#1d9bf0c4',
  breadcrumbText: 'gray',
  acytiveBreadcrumbText: '#ffffff',
  selectedCheckBox: '#1d9bf0c4',
  green: '#6DD0A3',
};

export default ligthVersion;
